### ISSUE TITLE
Train with multiple dataset already split up

### ISSUE THREAD

**Issue by HenryPDT** [ArgoHA/custom_d_fine#22]
Hi there,
Great work you are doing here, great that your repo supports data in YOLO format, all of my data is in YOLO format so its a pain to have to convert to COCO to use these frameworks, especially when you have multiple datasets to train with. What im wondering is how do I start training when I have multiple datasets and they are already split into train and val. Since I see that your script essentially just takes in the path in csv for training, I wonder if this is already possible in anyway, or do I have to make the code to do so? 

Also is it required to convert images to jpg in the preprocess? Im assuming png should still be fine, and the conversions is to reduce the file size for less storage and faster loading/tranfer? 

Below is an example my datasets structure, which contains many different datasets which have already been split up previously
 ```
ML_Datasets
│   ├── my_cool_dataset
│   ├── │   ├── day_scenes
│   ├── │   ├── │   ├── train
│   ├── │   ├── │   ├── │   ├── images
│   ├── │   ├── │   ├── │   ├──   ├── image_day_cam1_001.jpg
│   ├── │   ├── │   ├── │   └── labels
│   ├── │   ├── │   ├── │   ├──   ├── image_day_cam1_001.txt
│   ├── │   ├── │   └── val
│   ├── │   ├── │   └── │   ├── images
│   ├── │   ├── │   └── │   ├──   ├── image_day_cam1_002.jpg
│   ├── │   ├── │   └── │   └── labels
│   ├── │   ├── │   └── │   ├──   ├── image_day_cam1_002.txt
│   ├── │   ├── night_scenes
│   ├── │   ├── │   ├── train
│   ├── │   ├── │   ├── │   ├── images
│   ├── │   ├── │   ├── │   ├──   ├── image_night_cam2_001.png
│   ├── │   ├── │   ├── │   └── labels
│   ├── │   ├── │   ├── │   ├──   ├── image_night_cam2_001.txt
│   ├── │   ├── │   └── val
│   ├── │   ├── │   └── │   ├── images
│   ├── │   ├── │   └── │   ├──   ├── image_night_cam2_002.png
│   ├── │   ├── │   └── │   └── labels
│   ├── │   ├── │   └── │   ├──   ├── image_night_cam2_002.txt
│   ├── generic_objects_dataset
│   ├── │   ├── train
│   ├── │   ├── │   ├── images
│   ├── │   ├── │   ├──   ├── obj_001.jpg
│   ├── │   ├── │   └── labels
│   ├── │   ├── │   ├──   ├── obj_001.txt
│   ├── │   ├── val
│   ├── │   ├── │   ├── images
│   ├── │   ├── │   ├──   ├── obj_002.jpg
│   ├── │   ├── │   └── labels
│   ├── │   ├── │   ├──   ├── obj_002.txt
│   ├── synthetic_data
│   ├── │   ├── train
│   ├── │   ├── │   ├── images
│   ├── │   ├── │   ├──   ├── synth_img_001.jpg
│   ├── │   ├── │   └── labels
│   ├── │   ├── │   ├──   ├── synth_img_001.txt
│   ├── │   ├── val
│   ├── │   ├── │   ├── images
│   ├── │   ├── │   ├──   ├── synth_img_002.jpg
│   ├── │   ├── │   └── labels
│   ├── │   ├── │   ├──   ├── synth_img_002.txt
```
Previously when I use yolov5, i used a yaml as below in order to train with multipe dataset:

```
path: ../ML_Datasets 
train:
  - my_cool_dataset/day_scenes/train/images
  - my_cool_dataset/night_scenes/train/images
  - generic_objects_dataset/train/images
  - synthetic_data/train/images
val:
  - my_cool_dataset/day_scenes/val/images
  - my_cool_dataset/night_scenes/val/images
  - generic_objects_dataset/val/images
  - synthetic_data/val/images
test: # Leave empty if you don't have a test set
names:
  0: car
  1: motorcycle
  2: truck
  3: bus
  4: bicycle
```
